### ISSUE TITLE
Instant crashes on NixOS

### ISSUE THREAD

**Issue by fufexan** [rharish101/ReGreet#32] opened 2023-06-17 23:03 UTC
Sometime after updating ReGreet in Nixpkgs to 0.1.1, it started crashing sway (or cage) continually, requiring me to manually kill the greetd service. From what I could see in the fast flickers, a window title appeared for ReGreet (unusual), but everything else looked normal. Even the log file looks normal, with debug enabled. I'll attach it here.
I've rolled back to 0.1.0 and it works completely fine.
Also, I've tried removing all the settings first but that did not seem to help.
[regreet_log.txt](https://github.com/rharish101/ReGreet/files/11780188/regreet_log.txt)

**Comment by rharish101** [comment] 2023-06-19 06:19
Could you clear the log file, and attach one with the failing session? The sessions at the start and at the end are all successful sessions.

**Comment by fufexan** [comment] 2023-06-19 14:43
[regreet_log.txt](https://github.com/rharish101/ReGreet/files/11789279/regreet_log.txt)
It's probably repeated about 7 times. That's the count it took for me to login to another tty and stop greetd.

**Comment by rharish101** [comment] 2023-06-21 06:34
The logs aren't revealing anything. Is there anything elsewhere, like greetd/sway/systemd logs? If not, you might have to bisect this. Try commit ccffff8, because everything up till then should just be fixes.

**Comment by fufexan** [comment] 2023-06-21 11:06
`ccffff8` works fine. I've now started bisecting, checking `f8022a0`.

**Comment by fufexan** [comment] 2023-06-21 11:31
https://github.com/rharish101/ReGreet/commit/f8022a03aff145ea531f1d8534aa29282dd3a458 seems to be the bad commit.

**Comment by rharish101** [comment] 2023-06-24 11:27
Ah, so it's the multi-monitor thing. A few more questions:
- How many monitors do you have?
- What's your GTK version?
- Could you post the terminal output of running ReGreet (within Sway/Cage)? There might be some GTK-related info.

**Comment by fufexan** [comment] 2023-06-24 14:05
- Only the builtin laptop screen at the time of the crashes
- `ldd` says `libgtk-4.so.1 => /nix/store/yg6mrlwckqc24a3k6ds4hx56m4nq2lpm-gtk4-4.10.3/lib/libgtk-4.so.1`
- I will try. In the meantime, I found something from `dmesg`
```
Jun 21 14:27:13 io kernel: traps: regreet[267527] general protection fault ip:7f270247da49 sp:7ffdd9187a10 error:0 in libgtk-4.so.1.1000.3[7f27020b9000+412000]
```

**Comment by rharish101** [comment] 2023-06-27 10:12
This is gonna be a weird debugging session, but:
1. Could you try building from the latest `main` branch, but after commenting out this line: https://github.com/rharish101/ReGreet/blob/61d871a0ee5c74230dfef8100d0c9bc75b309203/src/gui/component.rs#L370
2. If it doesn't work, try additionally commenting out these lines: https://github.com/rharish101/ReGreet/blob/61d871a0ee5c74230dfef8100d0c9bc75b309203/src/gui/component.rs#L330-L338
3. If that still doesn't work, try adding `return;` right before this line (effectively ignoring the function `choose_monitor`): https://github.com/rharish101/ReGreet/blob/61d871a0ee5c74230dfef8100d0c9bc75b309203/src/gui/model.rs#L133

Let me know which step worked for you.

**Comment by fufexan** [comment] 2023-06-27 20:56
Trying suggestion #1 it does not crash anymore. ReGreet is now "maximized" and not fullscreen (borders and titlebar are showing).

**Comment by rharish101** [comment] 2023-06-28 06:36
Okay, so for some reason, the GTK function `fullscreen_on_monitor` leads to a crash on your system. I'll have to investigate if that function has some caveats that apply to your case that I didn't consider. If I can't find any, we'll have to raise an issue upstream.

**Comment by addy419** [comment] 2023-07-01 20:04
@rharish101 @fufexan I am having the same issue on NixOS.

**Comment by rharish101** [comment] 2023-07-27 21:35
Sorry for the long delay. I couldn't find anything in the documentation about weird behaviours with `fullscreen_on_monitor`. Since it's been a while, @fufexan could you try with the latest GTK version? If it still doesn't work, I can open an issue upstream and tag you.

**Comment by fufexan** [comment] 2023-07-29 20:11
@rharish101 tried with the latest version in nixpkgs, and it behaves the same.

**Comment by Mikilio** [comment] 2023-08-24 15:53
I have the same issue what I also noticed was that my themes aren't applied during the flickering as well. For some reason a workaround for this on sway seems to be to add this line to my sway config:
```
    output * background ${theme.wallpaper} fill
```
for reference my whole config:

```
    exec ${pkgs.dbus}/bin/dbus-update-activation-environment --systemd --all

    output DP-1 pos 0 0

    output DP-1 pos 0 0

    input * {
      xkb_numlock enabled
    }
    seat seat0 xcursor_theme Bibata-Modern-Classic 24
    xwayland disable

    bindsym Mod4+shift+e exec swaynag \
      -t warning \
      -m 'What do you want to do?' \
      -b 'Poweroff' 'systemctl poweroff' \
      -b 'Reboot' 'systemctl reboot'

    exec "${lib.getExe config.programs.regreet.package} -l debug; swaymsg exit"
```

The workaround might be a fluke that happened a lot in succession, because the bug itself isn't something I'm able to reproduce consistently which leads me to think that the issue has something to do with how my monitors behave.

**Comment by RicArch97** [comment] 2023-12-04 00:13
I just enabled this software in my NixOS config, and it runs fine without crashing.

**Comment by Mikilio** [comment] 2023-12-14 17:32
can confirm this issue is solved for me, too

**Comment by willswats** [comment] 2023-12-15 13:22
Works for me on NixOS 24.05 with Hyprland, on Regreet 0.1.1, the only issue that occurs for me is #11.

**Comment by rharish101** [comment] 2023-12-31 11:18
Huh, strange. I was thinking of opening an issue with upstream GTK due to the bug that @fufexan helped narrow down, but put off since they wanted a minimal reproducible code with the bug.

I guess they fixed it in the meantime, and so I'm going to close this. Let me know if it still affects a few people, and then I'll re-open it.

**Closed by rharish101** 2023-12-31 11:18 UTC
Labels: bug, multi monitor
