### ISSUE TITLE
Give more useful error message when /etc/login.defs isn't present

### ISSUE THREAD

**Issue by Merlin04** [rharish101/ReGreet#89] opened 2024-10-02 06:23 UTC
Some distros (in my case, opensuse tumbleweed) don't have an /etc/login.defs - instead, it's located at /usr/etc/login.defs. If you try running regreet on a standard tumbleweed system, it panics with a generic unable to read file error, not saying what file it tried to read. Ideally, it would try the /usr path if the normal path isn't found, and if that still doesn't exist, then print an error indicating that neither file was found.

**Comment by max-ishere** [comment] 2024-10-12 15:20
Hmm, I looked up the `man login.defs` for tumbleweed:
https://manpages.opensuse.org/Tumbleweed/login_defs/login.defs.5.en.html
and even there it says the file should be at /etc.

> The /etc/login.defs file defines the site-specific configuration for the shadow password suite. This file is required. Absence of this file will not prevent system operation, but will probably result in undesirable operation.

:shrug: ...

Anyways I can work on fixing this one.

As for the location of the file, are you sure it only exists in /usr and not symlinked to /etc? If it is actually moved there I can add an ENV to override it's location at build time.

And considering the fact that regreet is not packaged on tumbleweeed (https://software.opensuse.org/search?q=regreet&baseproject=openSUSE%3AFactory) you have probably built it from source so I think you can test out the patch.

**Comment by max-ishere** [comment] 2024-10-14 11:30
@Merlin04 can you test #91 please, there should be a warning in the logs now. You dont have to install it system wide, just run

```sh
fakegreet 'cargo r`
```

If the issue is resolved, I can add a build time env constant and that should resolve this one

**Comment by Merlin04** [comment] 2024-10-19 01:41
Sorry for the delay - it appears to be working, I'm getting this error in the logs when I test with #91:
> 2024-10-18T18:39:02.341228919-07:00  WARN regreet::sysutil: Failed to read `/etc/login.defs`

Maybe the man page is out of date? but it appears that the file in `/etc/login.defs` just doesn't exist: https://forums.opensuse.org/t/on-installing-keyd-configuration-error-unknown-item-useradd-cmd/179060/4

**Comment by max-ishere** [comment] 2024-10-19 09:30
Welp, at least it doesn't panic anymore. I will work on adding a const override via ENVs, should probably add an override for the default values for UID_MIN and UID_MAX because the defaults may differ across distros too?...

**Comment by max-ishere** [comment] 2024-10-19 09:40
@rharish101 I think the override path should allow `:` separated paths, this way the source can hardcode the default to be both etc and usr, but I doubt the distro maintainers would find this useful...

**Comment by max-ishere** [comment] 2024-10-19 17:03
@Merlin04 I pushed an update to #91, it will now try all paths from a list and this list can be overriden at compile time. So now it should work on your distro without you doing anything special.

**Comment by max-ishere** [comment] 2024-10-20 11:57
@Merlin04 does the :tada: mean the issue is resolved by #91?

**Comment by Merlin04** [comment] 2024-10-20 15:18
Yeah, I think so!

**Comment by max-ishere** [comment] 2024-10-20 16:54
Okie

**Comment by mbekkomo** [comment] 2024-11-04 21:18
In Solus, neither `/etc/login.defs` nor `/usr/etc/login.defs` exist.

**Comment by mbekkomo** [comment] 2024-11-04 21:22
I just rechecked, it exists in `/usr/share/defaults/etc/login.defs`.

**Comment by max-ishere** [comment] 2024-11-05 09:58
I did a quick search and [this post](https://discuss.getsol.us/d/8046-failed-login-delay/3
) says its in `/etc`. My suspicion is that the `/usr/share/defaults` contains default values and is not supposed to be mutated. However it could be the same confusing path as [`/etc/default/grub`](https://www.gnu.org/software/grub/manual/grub/grub.html#Simple-configuration). This is easy to verify. Can you open your `/usr/share/defaults/etc/login.defs`, remember the UID_MAX value and then run `useradd` to change it:

```sh
useradd --key UID_MIN=60001
```

[`man useradd`](https://man.archlinux.org/man/useradd.8#OPTIONS)

Then see if the override is placed into /usr or a file is created in /etc.

@Merlin04 I am assuming that for you, it would just go into /usr/etc/login.defs, but can you check too?

**Comment by rharish101** [comment] 2024-12-22 13:13
Should be resolved by #91. Please lemme know if it didn't resolve the issue.

**Closed by rharish101** 2024-12-22 13:13 UTC
