### ISSUE TITLE
Multi-monitor Support on Cage

### ISSUE THREAD

**Issue by CaitlinDavitt** [rharish101/ReGreet#11] opened 2023-03-03 22:01 UTC
Hello, I was trying to use ReGreet with two monitors, and it ended up spanning one login screen across the middle of both monitors, which was difficult to use. Would there be a way for it to either have ReGreet on just one monitor, have one screen with the login and one with just the background, or have ReGreet on both of the monitors? Thanks.

**Comment by rharish101** [comment] 2023-03-12 12:43
Could you post your compositor (the one used to launch ReGreet) config? I tried this with Sway, and it opens a login screen on a single monitor, while the other monitor stays greyed out.

**Comment by rharish101** [comment] 2023-03-12 12:56
I can also set the other monitors to display the background image using `swaybg` in the Sway config. For this, I added this line to my Sway config:
```
exec swaybg --image "/path/to/background/image.jpg"
```

Though, this method has the downside that you need to install another application `swaybg` to set the background image.

**Comment by TheSunCat** [comment] 2023-03-26 08:53
I can reproduce this with an external monitor plugged in. Here's my Sway config:
```ini
exec "regreet; swaymsg exit"

bindsym Mod4+shift+e exec swaynag \
-t warning \
-m 'What do you want to do?' \
-b 'Poweroff' 'systemctl poweroff' \
-b 'Reboot' 'systemctl reboot'

include /etc/sway/config.d/*
```

**Comment by rharish101** [comment] 2023-03-29 21:52
@TheSunCat Could you also post the contents of all files under `/etc/sway/config.d`? I had nearly the same config (without the `bindsym`) when I last tested this.

**Comment by rharish101** [comment] 2023-05-07 20:05
If anyone still has this issue, please try the latest `main` branch code. I added a commit for some basic multi monitor support, which should theoretically help with this issue.

**Comment by zombiehoffa** [comment] 2023-06-07 00:51
I can confirm that the git aur package as of today had this issue with cage for me but when I switched to sway as above it worked fine.

**Comment by rharish101** [comment] 2023-06-07 06:52
Okay, in that case I'll close this issue. If anyone still has issues, feel free to comment here. I'll then reopen this issue.

**Comment by Vosjedev** [comment] 2023-11-12 13:05
I am trying to get this to work with cage, because I do not use sway by default. Tried with hyprland, did not work...

**Comment by ValouBambou** [comment] 2023-12-10 23:29
The issue is still here (arch linux official package) using cage, also I tried to use sway instead but the window with login, session doesn't appear.

**Comment by ericlay** [comment] 2023-12-21 21:03
Came here because I'm suffering the same issue. I am using the arch official package and cage on hyprland.

**Comment by max-ishere** [comment] 2024-10-20 10:43
You can make it on one monitor with this option:

```
-m <mode>

Set the multi-monitor behavior. Supported modes are: last Cage uses only the last connected monitor. extend Cage extends the display across all connected monitors.
```

https://man.archlinux.org/man/extra/cage/cage.1.en#OPTIONS

Basically do `cage -mlast -- regreet`, you probably also want `-d -s`, lookup what those mean in cage.

**Comment by rharish101** [comment] 2024-12-22 14:48
Can someone else with a multi-monitor setup test this with Cage to see if the issue still persists? If not, I'll close the issue.

**Comment by max-ishere** [comment] 2024-12-22 16:16
I have been using regreet with cage, multiple monitors, never had any issues.

```sh
cage -d -s -mlast -- regreet ...
```

**Closed** 2024-12-22 16:23 UTC
Labels: confirmed bug, multi monitor
